# -*- coding: utf-8 -*-
"""Programa_de_compra.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y7559FDywSlZ_w8jbBCmcP0N_GZ0hxCf
"""

#Sistema de papelaria

#o cliente pode escolher dentre as opções: comprar canetas, sulfites ou cola.

#e depois poderá pagar
#OPÇÕES: cartão, dinheiro ou pix
#atendente se despede

def atendimento():
     print("Olá, primeiro escolha o que deseja comprar e depois a forma de pagamento.")
     escolha = int(input("Digite 1 para comprar e logo após você será direcionado para as opções de pagamento->"))
     if escolha == 1:
          escolha_compra()
          escolha_pagamento()
     else:
        print("Você não escolheu o que deseja comprar")
        escolha_compra()


def escolha_compra():
  opcao_compra = input("Escolha uma opção: a -canetas, b - sulfite, c - cola ->")
  if opcao_compra =='a':
     print("Irei pegar as canetas disponíveis.")
  elif opcao_compra == 'b':
     print('OK, você escolheu sulfite')
  elif opcao_compra  == 'c':
      print('Só um momento, já vou buscar as colas que temos em estoque.')
  else:
    print("Não temos esse produto, por favor escolha novamente.")
    escolha_compra()

def escolha_pagamento():
  opcao_pagamento = input("Escolha uma opção para pagamento: a -cartão, b - dinheiro, c - pix ->")
  if opcao_pagamento =='a':
     print("Irei pegar a maquininha.")
  elif opcao_pagamento == 'b':
     print('OK, você escolheu dinheiro. Já vou pegar o seu troco')
  elif opcao_pagamento  == 'c':
      print('Você escolheu pix, irei te passar o QR code.')
  else:
    print("Temos apenas as seguintes opções de pagamento: cartão, dinheiro ou pix. Por favor escolha novamente.")
    escolha_pagamento()


atendimento()
print("Muito obrigado pela sua compra. Até logo !")